<?php

namespace Maximaster\Redmine2TuleapPlugin\Enum;

use MyCLabs\Enum\Enum;

/**
 * @method static self ADMINDELEGATION()
 * @method static self AGILEDASHBOARD()
 * @method static self API_EXPLORER()
 * @method static self ARCHIVEDELETEDITEMS()
 * @method static self ARTIFACTSFOLDERS()
 * @method static self BUGZILLA_REFERENCE()
 * @method static self CAPTCHA()
 * @method static self CARDWALL()
 * @method static self CREATE_TEST_ENV()
 * @method static self CROSSTRACKER()
 * @method static self DOCMAN()
 * @method static self DOCUMENT()
 * @method static self DYNAMIC_CREDENTIALS()
 * @method static self EMBED()
 * @method static self FORUMML()
 * @method static self FRS()
 * @method static self GIT()
 * @method static self GITLFS()
 * @method static self GRAPHONTRACKERSV5()
 * @method static self HUDSON()
 * @method static self HUDSON_GIT()
 * @method static self HUDSON_SVN()
 * @method static self LABEL()
 * @method static self LDAP()
 * @method static self MEDIAWIKI()
 * @method static self MFA()
 * @method static self MULTI_PROJECT_BACKLOG()
 * @method static self OAUTH2_SERVER()
 * @method static self OPENIDCONNECTCLIENT()
 * @method static self PLUGINSADMINISTRATION()
 * @method static self PROFTPD()
 * @method static self PROJECT_OWNERSHIP()
 * @method static self PROJECTLINKS()
 * @method static self PROJECTMILESTONES()
 * @method static self PROMETHEUS_METRICS()
 * @method static self PULLREQUEST()
 * @method static self REDMINE2TULEAP()
 * @method static self REFERENCEALIAS_CORE()
 * @method static self REFERENCEALIAS_GIT()
 * @method static self REFERENCEALIAS_MEDIAWIKI()
 * @method static self REFERENCEALIAS_SVN()
 * @method static self REFERENCEALIAS_TRACKER()
 * @method static self RELEASE_WIDGET()
 * @method static self STATISTICS()
 * @method static self SVN()
 * @method static self TASKBOARD()
 * @method static self TEE_CONTAINER()
 * @method static self TEMPLATE()
 * @method static self TESTMANAGEMENT()
 * @method static self TESTPLAN()
 * @method static self TEXTUALREPORT()
 * @method static self TIMETRACKING()
 * @method static self TRACKER()
 * @method static self TRACKER_DATE_REMINDER()
 * @method static self TRACKER_ENCRYPTION()
 * @method static self TULEAP_SYNCHRO()
 * @method static self USERLOG()
 * @method static self VELOCITY()
 * @method static self WEBDAV()
 */
class TuleapPluginEnum extends Enum
{
    public const ADMINDELEGATION = 'admindelegation';
    public const AGILEDASHBOARD = 'agiledashboard';
    public const API_EXPLORER = 'api_explorer';
    public const ARCHIVEDELETEDITEMS = 'archivedeleteditems';
    public const ARTIFACTSFOLDERS = 'artifactsfolders';
    public const BUGZILLA_REFERENCE = 'bugzilla_reference';
    public const CAPTCHA = 'captcha';
    public const CARDWALL = 'cardwall';
    public const CREATE_TEST_ENV = 'create_test_env';
    public const CROSSTRACKER = 'crosstracker';
    public const DOCMAN = 'docman';
    public const DOCUMENT = 'document';
    public const DYNAMIC_CREDENTIALS = 'dynamic_credentials';
    public const EMBED = 'embed';
    public const FORUMML = 'forumml';
    public const FRS = 'frs';
    public const GIT = 'git';
    public const GITLFS = 'gitlfs';
    public const GRAPHONTRACKERSV5 = 'graphontrackersv5';
    public const HUDSON = 'hudson';
    public const HUDSON_GIT = 'hudson_git';
    public const HUDSON_SVN = 'hudson_svn';
    public const LABEL = 'label';
    public const LDAP = 'ldap';
    public const MEDIAWIKI = 'mediawiki';
    public const MFA = 'mfa';
    public const MULTI_PROJECT_BACKLOG = 'multi_project_backlog';
    public const OAUTH2_SERVER = 'oauth2_server';
    public const OPENIDCONNECTCLIENT = 'openidconnectclient';
    public const PLUGINSADMINISTRATION = 'pluginsadministration';
    public const PROFTPD = 'proftpd';
    public const PROJECT_OWNERSHIP = 'project_ownership';
    public const PROJECTLINKS = 'projectlinks';
    public const PROJECTMILESTONES = 'projectmilestones';
    public const PROMETHEUS_METRICS = 'prometheus_metrics';
    public const PULLREQUEST = 'pullrequest';
    public const REDMINE2TULEAP = 'redmine2tuleap';
    public const REFERENCEALIAS_CORE = 'referencealias_core';
    public const REFERENCEALIAS_GIT = 'referencealias_git';
    public const REFERENCEALIAS_MEDIAWIKI = 'referencealias_mediawiki';
    public const REFERENCEALIAS_SVN = 'referencealias_svn';
    public const REFERENCEALIAS_TRACKER = 'referencealias_tracker';
    public const RELEASE_WIDGET = 'release_widget';
    public const STATISTICS = 'statistics';
    public const SVN = 'svn';
    public const TASKBOARD = 'taskboard';
    public const TEE_CONTAINER = 'tee_container';
    public const TEMPLATE = 'template';
    public const TESTMANAGEMENT = 'testmanagement';
    public const TESTPLAN = 'testplan';
    public const TEXTUALREPORT = 'textualreport';
    public const TIMETRACKING = 'timetracking';
    public const TRACKER = 'tracker';
    public const TRACKER_DATE_REMINDER = 'tracker_date_reminder';
    public const TRACKER_ENCRYPTION = 'tracker_encryption';
    public const TULEAP_SYNCHRO = 'tuleap_synchro';
    public const USERLOG = 'userlog';
    public const VELOCITY = 'velocity';
    public const WEBDAV = 'webdav';
}
